### ISSUE TITLE
Ingress extensions/v1beta1 gets deprecated in Kubernetes 1.22

### ISSUE THREAD

**Issue by eumel8** [gnuu-de/k8s#1]
Ref:
https://github.com/gnuu-de/k8s/blob/96aecf75cd361d0abe9352ac28d9f95ade66506f/nginx/ingress.yaml#L2
https://github.com/gnuu-de/k8s/blob/96aecf75cd361d0abe9352ac28d9f95ade66506f/api/ingress.yaml#L2
https://github.com/gnuu-de/k8s/blob/96aecf75cd361d0abe9352ac28d9f95ade66506f/matrix/ingress.yaml#L2

Caused by Traefik 1.7, fixed in 2.4:

https://github.com/k3s-io/k3s/issues/1141

**Comment by balibebas** [comment]
I'm curious what the upgrade path is here. Are those using older versions of K3s going to receive support on this deprecation or will they have to update to a newer version of K3s and undergo the Traefik 2 upgrade at the same time?

**Comment by eumel8** [comment]
Announced for 1.20 but v1.20.4+k3s1 is still shipped with Traefik 1.x
https://github.com/k3s-io/k3s/blob/master/ROADMAP.md#v120---december-2020

**Comment by eumel8** [comment]
fix in https://github.com/gnuu-de/k8s/commit/bdde1bc53349320fe3b1c4d89384a40ee13e3ce0
Upgrade Kubernetes 1.21.4 + Traefik v2
